### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [MaxKalinin92/maxkalinin.github.io#1]
Hello Max, looks almost good, but I see the issue with margins at the bottom
![image](https://user-images.githubusercontent.com/5592397/92307080-8ac00c80-ef9c-11ea-8d36-60b26dff5c1e.png)

**Comment by MaxKalinin92** [comment]
I fixed the problem. The task is ready for rewiew

**Comment by ilya4321** [comment]
Another issue on small height screen
![image](https://user-images.githubusercontent.com/5592397/92456871-284d5300-f1cc-11ea-9729-73a04ed8ef83.png)

**Comment by MaxKalinin92** [comment]
fixed. ready for review

**Comment by ilya4321** [comment]
Thanks, looking quite well! The task is accepted
